RentalMobile/RentalMobile/Controllers/Listing/Projects/ProjectsController.cs
using System.Linq;
using System.Web.Mvc;
using RentalMobile.Helpers.Base;
using RentalModel.Repository.Generic.UnitofWork;

namespace RentalMobile.Controllers.Listing.Projects
{ 
    public class ProjectsController : BaseController
    {

        public ProjectsController(IGenericUnitofWork uow)
        {
            UnitofWork = uow;
        }

        public ViewResult Index()
        {
            return View(UnitofWork.ProjectRepository.All.ToList());
        }


        //Only Specialist Make an Offer
        //Make sure to show it when they are log in
        public ViewResult MakeOffer()
        {
            return View();
        }
    }
}

RentalMobile/RentalMobile/Controllers/PublicProfile/ProjectDetailController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using RentalMobile.Helpers.Base;
using RentalMobile.Helpers.Core;
using RentalModel.Repository.Generic.UnitofWork;

namespace RentalMobile.Controllers.PublicProfile
{ 
    public class ProjectDetailController : BaseController
    {

        public ProjectDetailController(IGenericUnitofWork uow,  IUserHelper userHelper)
        {
            UnitofWork = uow;
            UserHelper = userHelper;
        }

        public ViewResult Index()
        {
            return View(UnitofWork.ProjectPhotoRepository.All.ToList());
        }

        [HttpPost]
        public ActionResult MakeOffer(FormCollection form)
        {
            TempData["startDate"] = form["HiddenStartDate"];
            TempData["endDate"] = form["HiddenEndDate"];
            TempData["ProjectId"] = form["HiddenProjectId"];
            return RedirectToAction("Confirm");
        }

        public ActionResult Confirm()
        {
            ViewBag.StartDate = TempData["startDate"];
            ViewBag.EndDate = TempData["endDate"];
            ViewBag.ProjectID = TempData["ProjectId"];
            return View();
        }

        [HttpPost]
        public ActionResult Confirm(FormCollection form)
        {

            //SpecialistID
            var specialistId = (Convert.ToInt32( form["HiddenProjectId"]));
            var specialist = UserHelper.SpecialistPrivateProfileHelper.GetPrivateProfileSpecialistBySpecialistId(specialistId);

            if (specialist == null)
            {
                return RedirectToAction("MakeOffer");
            }


            ////<Summary>///
            //TODO The below//
            //Make sure Project is still Open, not closed by Owner, Agent or finished.

            //Offer Data
            //More Work
            //You need to put them in the view so you can grab them

            //It Should be already included
            var startdate = form["StartDate"];
            var enddate = form["EndDate"];
            //It Should be already included

            var amount = form["Amount"];
            var currency = form["Currency"];
            var quicknote = form["Quick Note"];

            //Insert into Owner, Agent Offer
            //Insert into Sepcialist submittted ofer
            //Do the confirmation.


            ////WHEN AMAZON PAYMENT SUCCEED
            //if (property != null)
            //{
            //    var posterrole = property.PosterRole.Trim();

            //    switch (posterrole)
            //    {

            //        case "Owner":
            //            //Insert into Pending Application
            //            if (property.PosterID != null)
            //                InsertOwnerPendingApplication(tenantrentalapplication.First(), (int)property.PosterID);
            //            ViewData["confirmationmsg"] = "Your Application had been succesfully submitted to the Owner.";

            //            //Confirmation that is has been posted
            //            break;

            //        case "Agent":
            //            //Insert into Pending Application
            //            if (property.PosterID != null)
            //                InsertAgentPendingApplication(tenantrentalapplication.First(), (int)property.PosterID);
            //            ViewData["confirmationmsg"] = "Pass";
            //            break;

            //    }
            //}
            return View();
        }

    }
}

RentalMobile/RentalMobile/Views/Projects/Index.cshtml
@using System.Globalization
@using RentalMobile.Helpers
@model IEnumerable<RentalMobile.Model.Models.Project>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Template/_ConceptLayoutPage.cshtml";
}
<section class="sixteen columns">
    <h2 class="remove-top">
        PROPERTY</h2>
    <!-- filters -->
    <form action="#" class="row">
        <!-- tag filters -->
        <ul class="filter-list ten alpha columns row">
            <li><a data-rel="all" class="current">All</a></li>
            <li><a data-rel="house">House</a></li>
            <li><a data-rel="duplex">Duplex</a></li>
            <li><a data-rel="townhouse">Townhouse</a></li>
            <li><a data-rel="apartment">Apartment</a></li>
            <li><a data-rel="loft">Loft</a></li>
            <li><a data-rel="office">Office</a></li>
            <li><a data-rel="condo">Condo</a></li>
        </ul>
        <div class="switcher fr">
            <a href="#" id="gridview" class="switcher"><i class="icon-layout"></i></a><a href="#"
                                                                                         id="listview" class="switcher active"><i class="icon-menu"></i></a>
        </div>
    </form>
    <div id="showing" class="panel">
        <section class="fifteen columns">
            <!-- List/Grid gallery -->
            <ul id="property-list" class="list-grid-gallery list">
                @foreach (var item in Model)
                {
                    <li class="prop-type all @Html.GetUnitType(item.ServiceTypeID)">
                        <article>
                            <figure class="five columns alpha">
                                @Html.ActionLink(Html.CountPhoto(item.ProjectID), "Edit", new { id = item.ProjectID }, new { @class = "camera" })
                                <img src="@item.PrimaryPhoto" class="scale-with-grid" width="280" height="185"
                                     alt="gallery" />
                            </figure>
                            <div class="nine columns omega">
                                <h4>
                                    @item.Address, @item.City, @item.State, @item.CountryCode</h4>
                                <ul class="prop-data">
                                    <li class="price">@Html.DisplayFor(modelItem => item.Budget)</li>
                                    @if (item.CountryCode != null)
                                    {
                                        if (item.Currency!= null)
                                        {
                                            <li class="new">@item.Currency.ToString(CultureInfo.InvariantCulture)
                                                <span style="color: #346993">@item.Currency.ToString(CultureInfo.InvariantCulture)</span></li>
                                        }
                                    }
                                </ul>
                                <p class="prop-webid">
                                    Unit ID #@Html.DisplayFor(modelItem => item.ProjectID)</p>
                  @*              <p class="propr-details">
                                    @Html.GetBedValue(item.) bedroom / @Html.GetBathroomValue(item.Bed) bathrom /
                                    @item.SquareFoot sqft
                                </p>*@
                                <p class="prop-extract">@Html.TruncateLongString(item.Description, 500)
                                </p>
                                <ul class="toolbar">
                                    <li>@Html.ActionLink("Select", "Index", "ProjectDetail", new { id = item.ProjectID }, null)</li>
                                </ul>
                            </div>
                        </article>
                    </li>
                }
            </ul>
            <!-- /.List -->
            <style>
                #container
                {
                    width: 100%;
                    text-align: center;
                }
                
                #left
                {
                    float: left;
                    width: 50px;
                    height: 20px;
                    background: #ff0000;
                }
                
                #center
                {
                    display: inline-block;
                    margin: 0 auto;
                    width: 50px;
                    height: 20px;
                    background: #00ff00;
                }
                
                #right
                {
                    float: right;
                    width: 50px;
                    height: 20px;
                    background: #0000ff;
                }
            </style>
        </section>
        <section class="fifteen columns">
            <!--Pagination-->
            <div id="container">
                <div id="left">
                    Previous</div>
                <div id="center">
                    Page 1 of 10</div>
                <div id="right">
                    Next</div>
            </div>
            <!--Pagination-->
        </section>
    </div>
</section>



<section class="sixteen columns" id="DesignDecision">
    <h2>
        Property</h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProjectID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ProjectID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProjectID })
                </td>
            </tr>
        }
    </table>
</section>
<!-- Scripts & Plugins
        ================================================== -->
<!-- BX Slider -->
<script src="../../Scripts/js/jquery.bxslider.min.js" type="text/javascript"></script>
<!--Fancybox Ligbox-->
<script src="../../Scripts/js/jquery.fancybox.js" type="text/javascript"></script>
<!--Fancybox Ligbox Thumbnails-->
<script src="../../Scripts/js/jquery.fancybox-thumbs.js" type="text/javascript"></script>
<!-- Tabs -->
<script src="../../Scripts/js/jquery.easytabs.min.js" type="text/javascript"></script>
<!-- jQuery dropdown -->
<script src="../../Scripts/js/jquery.dropdown.js" type="text/javascript"></script>
<!-- Tipsy -->
<script src="../../Scripts/js/jquery.tipsy.js" type="text/javascript"></script>
<!-- FitVids -->
<script src="../../Scripts/js/fitvids.min.js" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function ($) {

        // Init Carousel	
        $('.bx-carousel').bxSlider({
            auto: true,
            minSlides: 1,
            maxSlides: 3,
            slideWidth: 300,
            slideMargin: 20,
            nextSelector: '#carousel-next',
            prevSelector: '#carousel-prev',
            pager: false
        });

        //Easy tabs
        $('.tab-container').easytabs();

        //FitVids
        $('#video').fitVids();

    });
</script>
<!-- Gallery switcher -->
<script src="../../Scripts/js/switcher.js" type="text/javascript"></script>
<!-- jQuery dropdown -->
<script src="../../Scripts/js/jquery.dropdown.js" type="text/javascript"></script>
<!-- Tipsy -->
<script src="../../Scripts/js/jquery.tipsy.js" type="text/javascript"></script>
<!-- Custom Scripts -->
<script src="../../Scripts/js/scripts.js" type="text/javascript"></script>

RentalMobile/RentalMobile/Views/Projects/MakeOffer.cshtml
@{
    ViewBag.Title = "MakeOffer";
}

<h2>MakeOffer</h2>